// // LocalStorage keys
// const KEYS = {
//   USER: 'justly_user',
//   GOALS: 'justly_goals',
//   HABITS: 'justly_habits',
//   TASKS: 'justly_tasks',
//   JOURNAL: 'justly_journal',
//   REFLECTIONS: 'justly_reflections',
//   CHAT_HISTORY: 'justly_chat_history',
//   ACHIEVEMENTS: 'justly_achievements',
//   SETTINGS: 'justly_settings',
//   ONBOARDING_COMPLETE: 'justly_onboarding_complete',
// };


// export interface User {
//   id: string;
//   name: string;
//   email: string;
//   avatar?: string;
//   createdAt: string;
// }

// export interface Goal {
//   id: string;
//   title: string;
//   description: string;
//   category: 'health' | 'career' | 'wellness' | 'relationships' | 'personal';
//   targetDate?: string;
//   createdAt: string;
//   progress: number;
// }

// export interface Habit {
//   id: string;
//   title: string;
//   description?: string;
//   category: 'health' | 'productivity' | 'mindfulness' | 'social' | 'learning';
//   frequency: 'daily' | 'weekly' | 'custom';
//   completedDates: string[];
//   streak: number;
//   createdAt: string;
//   goalId?: string;
//   icon?: string;
//   color?: string;
// }

// export interface Task {
//   id: string;
//   title: string;
//   description?: string;
//   completed: boolean;
//   date: string;
//   habitId?: string;
//   goalId?: string;
//   priority: 'low' | 'medium' | 'high';
//   createdAt: string;
// }

// export interface JournalEntry {
//   id: string;
//   date: string;
//   content: string;
//   mood: 'great' | 'good' | 'okay' | 'low' | 'difficult';
//   tags: string[];
//   autoGenerated: boolean;
//   chatSummary?: string;
//   reflectionSummary?: string;
//   createdAt: string;
// }

// export interface Reflection {
//   id: string;
//   date: string;
//   wins: string[];
//   challenges: string[];
//   gratitude: string[];
//   lessonsLearned: string;
//   mood: 'great' | 'good' | 'okay' | 'low' | 'difficult';
//   energyLevel: number;
//   createdAt: string;
// }

// export interface ChatMessage {
//   id: string;
//   role: 'user' | 'assistant';
//   content: string;
//   timestamp: string;
// }

// export interface Achievement {
//   id: string;
//   title: string;
//   description: string;
//   icon: string;
//   unlockedAt?: string;
//   category: 'streak' | 'milestone' | 'special';
// }

// export interface Settings {
//   notifications: boolean;
//   morningPrepTime: string;
//   eveningReflectionTime: string;
//   theme: 'light' | 'dark' | 'system';
//   privacy: {
//     shareAnalytics: boolean;
//     showStreak: boolean;
//   };
// }

// // Helper functions
// const generateId = () => Math.random().toString(36).substring(2, 15);

// const getToday = () => new Date().toISOString().split('T')[0];

// const API_URL = "http://localhost:5000/api/auth";

// // User
// export const getUser = (): User | null => {
//   const data = localStorage.getItem(KEYS.USER);
//   return data ? JSON.parse(data) : null;
// };

// export const setUser = (user: User) => {
//   localStorage.setItem(KEYS.USER, JSON.stringify(user));
// };

// export const createUser = async (
//   name: string,
//   email: string,
//   password: string
// ): Promise<User> => {
//   const res = await fetch(`${API_URL}/signup`, {
//     method: "POST",
//     headers: { "Content-Type": "application/json" },
//     body: JSON.stringify({ name, email, password }),
//   });

//   if (!res.ok) throw new Error("Signup failed");

//   const user = await res.json();
//   setUser(user);
//   return user;
// };

// export const loginUser = async (
//   email: string,
//   password: string
// ): Promise<User | null> => {
//   const res = await fetch(`${API_URL}/login`, {
//     method: "POST",
//     headers: { "Content-Type": "application/json" },
//     body: JSON.stringify({ email, password }),
//   });

//   if (!res.ok) return null;

//   const user = await res.json();
//   setUser(user);
//   return user;
// };

// export const logoutUser = () => {
//   localStorage.removeItem(KEYS.USER);
//   localStorage.removeItem(KEYS.ONBOARDING_COMPLETE);
// };

// const ONBOARDING_API = "http://localhost:5000/api/onboarding";

// // ---------------- GOALS ----------------

// export const getGoals = async (): Promise<Goal[]> => {
//   const user = getUser();
//   if (!user) return [];

//   const res = await fetch(`${ONBOARDING_API}/goals/${user.id}`);
//   if (!res.ok) throw new Error("Failed to fetch goals");

//   const data = await res.json();

//   return data.map((g: any) => ({
//     id: g.id,
//     title: g.title,
//     description: g.description,
//     category: g.category,
//     createdAt: g.created_at,
//     progress: g.progress ?? 0,
//     targetDate: g.target_date ?? undefined,
//   }));
// };

// export const addGoal = async (
//   goal: Omit<Goal, "id" | "createdAt" | "progress">
// ): Promise<Goal> => {
//   const user = getUser();
//   if (!user) throw new Error("Not authenticated");

//   const res = await fetch(`${ONBOARDING_API}/goals`, {
//     method: "POST",
//     headers: { "Content-Type": "application/json" },
//     body: JSON.stringify({ ...goal, userId: user.id }),
//   });

//   if (!res.ok) throw new Error("Failed to add goal");

//   const g = await res.json();

//   return {
//     id: g.id,
//     title: g.title,
//     description: g.description,
//     category: g.category,
//     createdAt: g.created_at,
//     progress: g.progress ?? 0,
//   };
// };

// export const deleteGoal = async (goalId: string) => {
//   await fetch(`${ONBOARDING_API}/goals/${goalId}`, {
//     method: "DELETE",
//   });
// };
// // ---------------- HABITS ----------------

// export const getHabits = async (): Promise<Habit[]> => {
//   const user = getUser();
//   if (!user) return [];

//   const res = await fetch(`${ONBOARDING_API}/habits/${user.id}`);
//   if (!res.ok) throw new Error("Failed to fetch habits");

//   const data = await res.json();

//   return data.map((h: any) => ({
//     id: h.id,
//     title: h.title,
//     description: h.description,
//     category: h.category,
//     frequency: h.frequency,
//     completedDates: h.completed_dates ?? [],
//     streak: h.streak ?? 0,
//     createdAt: h.created_at,
//   }));
// };

// export const addHabit = async (
//   habit: Omit<Habit, "id" | "createdAt" | "completedDates" | "streak">
// ): Promise<Habit> => {
//   const user = getUser();
//   if (!user) throw new Error("Not authenticated");

//   const res = await fetch(`${ONBOARDING_API}/habits`, {
//     method: "POST",
//     headers: { "Content-Type": "application/json" },
//     body: JSON.stringify({ ...habit, userId: user.id }),
//   });

//   if (!res.ok) throw new Error("Failed to add habit");

//   const h = await res.json();

//   return {
//     id: h.id,
//     title: h.title,
//     description: h.description,
//     category: h.category,
//     frequency: h.frequency,
//     completedDates: [],
//     streak: 0,
//     createdAt: h.created_at,
//   };
// };

// export const completeHabit = async (habitId: string) => {
//   await fetch(`${ONBOARDING_API}/habits/${habitId}/complete`, {
//     method: "POST",
//   });
// };

// export const uncompleteHabit = async (habitId: string) => {
//   await fetch(`${ONBOARDING_API}/habits/${habitId}/uncomplete`, {
//     method: "POST",
//   });
// };

// export const deleteHabit = async (habitId: string) => {
//   await fetch(`${ONBOARDING_API}/habits/${habitId}`, {
//     method: "DELETE",
//   });
// };


// // Tasks
// export const getTasks = (date?: string): Task[] => {
//   const data = localStorage.getItem(KEYS.TASKS);
//   const tasks: Task[] = data ? JSON.parse(data) : [];
//   if (date) {
//     return tasks.filter(t => t.date === date);
//   }
//   return tasks;
// };

// export const saveTasks = (tasks: Task[]) => {
//   localStorage.setItem(KEYS.TASKS, JSON.stringify(tasks));
// };

// export const addTask = (task: Omit<Task, 'id' | 'createdAt'>): Task => {
//   const newTask: Task = {
//     ...task,
//     id: generateId(),
//     createdAt: new Date().toISOString(),
//   };
//   const tasks = getTasks();
//   tasks.push(newTask);
//   saveTasks(tasks);
//   return newTask;
// };

// export const toggleTask = (id: string) => {
//   const tasks = getTasks();
//   const task = tasks.find(t => t.id === id);
//   if (task) {
//     task.completed = !task.completed;
//     saveTasks(tasks);
//   }
// };

// export const deleteTask = (id: string) => {
//   const tasks = getTasks().filter(t => t.id !== id);
//   saveTasks(tasks);
// };

// // Journal
// export const getJournalEntries = (): JournalEntry[] => {
//   const data = localStorage.getItem(KEYS.JOURNAL);
//   return data ? JSON.parse(data) : [];
// };

// export const saveJournalEntries = (entries: JournalEntry[]) => {
//   localStorage.setItem(KEYS.JOURNAL, JSON.stringify(entries));
// };

// export const addJournalEntry = (entry: Omit<JournalEntry, 'id' | 'createdAt'>): JournalEntry => {
//   const newEntry: JournalEntry = {
//     ...entry,
//     id: generateId(),
//     createdAt: new Date().toISOString(),
//   };
//   const entries = getJournalEntries();
//   entries.unshift(newEntry);
//   saveJournalEntries(entries);
//   return newEntry;
// };

// export const getJournalByDate = (date: string): JournalEntry | undefined => {
//   return getJournalEntries().find(e => e.date === date);
// };

// // Reflections
// export const getReflections = (): Reflection[] => {
//   const data = localStorage.getItem(KEYS.REFLECTIONS);
//   return data ? JSON.parse(data) : [];
// };

// export const saveReflections = (reflections: Reflection[]) => {
//   localStorage.setItem(KEYS.REFLECTIONS, JSON.stringify(reflections));
// };

// export const addReflection = (reflection: Omit<Reflection, 'id' | 'createdAt'>): Reflection => {
//   const newReflection: Reflection = {
//     ...reflection,
//     id: generateId(),
//     createdAt: new Date().toISOString(),
//   };
//   const reflections = getReflections();
//   reflections.unshift(newReflection);
//   saveReflections(reflections);
//   return newReflection;
// };

// export const getReflectionByDate = (date: string): Reflection | undefined => {
//   return getReflections().find(r => r.date === date);
// };

// // Chat History
// export const getChatHistory = (): ChatMessage[] => {
//   const data = localStorage.getItem(KEYS.CHAT_HISTORY);
//   return data ? JSON.parse(data) : [];
// };

// export const saveChatHistory = (messages: ChatMessage[]) => {
//   localStorage.setItem(KEYS.CHAT_HISTORY, JSON.stringify(messages));
// };

// export const addChatMessage = (message: Omit<ChatMessage, 'id' | 'timestamp'>): ChatMessage => {
//   const newMessage: ChatMessage = {
//     ...message,
//     id: generateId(),
//     timestamp: new Date().toISOString(),
//   };
//   const history = getChatHistory();
//   history.push(newMessage);
//   saveChatHistory(history);
//   return newMessage;
// };

// export const clearChatHistory = () => {
//   localStorage.removeItem(KEYS.CHAT_HISTORY);
// };

// // Achievements
// export const getAchievements = (): Achievement[] => {
//   const data = localStorage.getItem(KEYS.ACHIEVEMENTS);
//   return data ? JSON.parse(data) : defaultAchievements;
// };

// export const unlockAchievement = (id: string) => {
//   const achievements = getAchievements();
//   const achievement = achievements.find(a => a.id === id);
//   if (achievement && !achievement.unlockedAt) {
//     achievement.unlockedAt = new Date().toISOString();
//     localStorage.setItem(KEYS.ACHIEVEMENTS, JSON.stringify(achievements));
//   }
// };

// const defaultAchievements: Achievement[] = [
//   { id: 'first_habit', title: 'First Step', description: 'Complete your first habit', icon: '🌱', category: 'milestone' },
//   { id: 'streak_7', title: 'Week Warrior', description: 'Maintain a 7-day streak', icon: '🔥', category: 'streak' },
//   { id: 'streak_30', title: 'Monthly Master', description: 'Maintain a 30-day streak', icon: '⭐', category: 'streak' },
//   { id: 'first_reflection', title: 'Mindful Moment', description: 'Complete your first reflection', icon: '🧘', category: 'milestone' },
//   { id: 'journal_10', title: 'Story Teller', description: 'Write 10 journal entries', icon: '📖', category: 'milestone' },
//   { id: 'goals_3', title: 'Goal Getter', description: 'Set 3 goals', icon: '🎯', category: 'milestone' },
//   { id: 'morning_prep_7', title: 'Early Bird', description: 'Complete 7 morning preps', icon: '🌅', category: 'streak' },
//   { id: 'chat_coach_10', title: 'Open Mind', description: 'Have 10 coaching sessions', icon: '💬', category: 'milestone' },
// ];

// // Settings
// export const getSettings = (): Settings => {
//   const data = localStorage.getItem(KEYS.SETTINGS);
//   return data ? JSON.parse(data) : defaultSettings;
// };

// export const saveSettings = (settings: Settings) => {
//   localStorage.setItem(KEYS.SETTINGS, JSON.stringify(settings));
// };

// const defaultSettings: Settings = {
//   notifications: true,
//   morningPrepTime: '07:00',
//   eveningReflectionTime: '21:00',
//   theme: 'light',
//   privacy: {
//     shareAnalytics: false,
//     showStreak: true,
//   },
// };

// // Onboarding
// export const setOnboardingComplete = async () => {
//   const user = getUser();
//   if (!user) return;

//   await fetch(`${ONBOARDING_API}/complete`, {
//     method: "POST",
//     headers: { "Content-Type": "application/json" },
//     body: JSON.stringify({ userId: user.id }),
//   });

//   localStorage.setItem(KEYS.ONBOARDING_COMPLETE, 'true');
// };

// export const isOnboardingComplete = async (): Promise<boolean> => {
//   const user = getUser();
//   if (!user) return false;

//   const res = await fetch(`${ONBOARDING_API}/status/${user.id}`);
//   const data = await res.json();
//   return data.completed;
// };


// // Helper to get today's date string
// export const getTodayString = () => getToday();






























































































 // LocalStorage keys 
const KEYS = {
  USER: 'justly_user',
  GOALS: 'justly_goals',
  HABITS: 'justly_habits',
  TASKS: 'justly_tasks',
  JOURNAL: 'justly_journal',
  REFLECTIONS: 'justly_reflections',
  CHAT_HISTORY: 'justly_chat_history',
  ACHIEVEMENTS: 'justly_achievements',
  SETTINGS: 'justly_settings',
  ONBOARDING_COMPLETE: 'justly_onboarding_complete',
};


export interface User {
  id: string;
  name: string;
  email: string;
  avatar?: string;
  createdAt: string;
}

export interface Goal {
  id: string;
  title: string;
  description: string;
  category: 'health' | 'career' | 'wellness' | 'relationships' | 'personal';
  targetDate?: string;
  createdAt: string;
  progress: number;
}

export interface Habit {
  id: string;
  title: string;
  description?: string;
  category: 'health' | 'productivity' | 'mindfulness' | 'social' | 'learning';
  frequency: 'daily' | 'weekly' | 'custom';
  completedDates: string[];
  streak: number;
  createdAt: string;
  goalId?: string;
  icon?: string;
  color?: string;
}

export interface Task {
  id: string;
  title: string;
  description?: string;
  completed: boolean;
  date: string;
  habitId?: string;
  goalId?: string;
  priority: 'low' | 'medium' | 'high';
  createdAt: string;
}

export interface JournalEntry {
  id: string;
  date: string;
  content: string;
  mood: 'great' | 'good' | 'okay' | 'low' | 'difficult';
  tags: string[];
  autoGenerated: boolean;
  chatSummary?: string;
  reflectionSummary?: string;
  createdAt: string;
}

export interface Reflection {
  id: string;
  date: string;
  wins: string[];
  challenges: string[];
  gratitude: string[];
  lessonsLearned: string;
  mood: 'great' | 'good' | 'okay' | 'low' | 'difficult';
  energyLevel: number;
  createdAt: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

export interface Achievement {
  id: string;
  title: string;
  description: string;
  icon: string;
  unlockedAt?: string;
  category: 'streak' | 'milestone' | 'special';
}

export interface Settings {
  notifications: boolean;
  morningPrepTime: string;
  eveningReflectionTime: string;
  theme: 'light' | 'dark' | 'system';
  privacy: {
    shareAnalytics: boolean;
    showStreak: boolean;
  };
}

// Helper functions
const generateId = () => Math.random().toString(36).substring(2, 15);

const getToday = () => new Date().toISOString().split('T')[0];

const API_URL = "http://localhost:5000/api/auth";

// User
export const getUser = (): User | null => {
  const data = localStorage.getItem(KEYS.USER);
  return data ? JSON.parse(data) : null;
};

export const setUser = (user: User) => {
  localStorage.setItem(KEYS.USER, JSON.stringify(user));
};

export const createUser = async (
  name: string,
  email: string,
  password: string
): Promise<User> => {
  const res = await fetch(`${API_URL}/signup`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ name, email, password }),
  });

  if (!res.ok) throw new Error("Signup failed");

  const user = await res.json();
  setUser(user);
  return user;
};

export const loginUser = async (
  email: string,
  password: string
): Promise<User | null> => {
  const res = await fetch(`${API_URL}/login`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ email, password }),
  });

  if (!res.ok) return null;

  const user = await res.json();
  setUser(user);
  return user;
};

export const logoutUser = () => {
  localStorage.removeItem(KEYS.USER);
  localStorage.removeItem(KEYS.ONBOARDING_COMPLETE);
};

const ONBOARDING_API = "http://localhost:5000/api/onboarding";
// Goals
export const getGoals = async (): Promise<Goal[]> => {
  const user = getUser();
  if (!user) return [];

  const res = await fetch(`${ONBOARDING_API}/goals/${user.id}`);
  const data = await res.json();

  return data.map((g: any) => ({
    ...g,
    createdAt: g.created_at,
  }));
};


export const saveGoals = (goals: Goal[]) => {
  localStorage.setItem(KEYS.GOALS, JSON.stringify(goals));
};

export const addGoal = async (
  goal: Omit<Goal, 'id' | 'createdAt' | 'progress'>
): Promise<Goal> => {
  const user = getUser();
  if (!user) throw new Error("Not authenticated");

  const res = await fetch(`${ONBOARDING_API}/goals`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ ...goal, userId: user.id }),
  });

  const saved = await res.json();
  return {
    ...saved,
    createdAt: saved.created_at,
  };
};


export const updateGoal = async (
  goalId: string,
  updates: Partial<Pick<Goal, "title" | "description" | "category" | "progress">>
): Promise<Goal> => {
  const res = await fetch(`${ONBOARDING_API}/goals/${goalId}`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(updates),
  });

  if (!res.ok) throw new Error("Failed to update goal");

  const updated = await res.json();

  return {
    ...updated,
    createdAt: updated.created_at,
  };
};


export const deleteGoal = async (goalId: string): Promise<void> => {
  const res = await fetch(`${ONBOARDING_API}/goals/${goalId}`, {
    method: "DELETE",
  });

  if (!res.ok) throw new Error("Failed to delete goal");
};


// Habits
export const getHabits = async (): Promise<Habit[]> => {
  const user = getUser();
  if (!user) return [];

  const res = await fetch(`${ONBOARDING_API}/habits/${user.id}`);
  if (!res.ok) throw new Error("Failed to fetch habits");

  const data = await res.json();

  return data.map((h: any) => ({
    ...h,
    createdAt: h.created_at,
    completedDates: h.completed_dates ?? [],
  }));
};


export const addHabit = async (
  habit: Omit<Habit, "id" | "createdAt" | "completedDates" | "streak">
): Promise<Habit> => {
  const user = getUser();
  if (!user) throw new Error("Not authenticated");

  const res = await fetch(`${ONBOARDING_API}/habits`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ ...habit, userId: user.id }),
  });

  if (!res.ok) throw new Error("Failed to add habit");

  const saved = await res.json();

  return {
    ...saved,
    createdAt: saved.created_at,
    completedDates: saved.completed_dates ?? [],
    streak: saved.streak ?? 0,
  };
};



export const completeHabit = async (habitId: string): Promise<void> => {
  const res = await fetch(`${ONBOARDING_API}/habits/${habitId}/complete`, {
    method: "POST",
  });

  if (!res.ok) throw new Error("Failed to complete habit");
};


export const uncompleteHabit = async (habitId: string): Promise<void> => {
  const res = await fetch(`${ONBOARDING_API}/habits/${habitId}/uncomplete`, {
    method: "POST",
  });

  if (!res.ok) throw new Error("Failed to uncomplete habit");
};


export const deleteHabit = async (habitId: string): Promise<void> => {
  const res = await fetch(`${ONBOARDING_API}/habits/${habitId}`, {
    method: "DELETE",
  });

  if (!res.ok) throw new Error("Failed to delete habit");
};


// Tasks
// ✅ TASKS (DB)
export const getTasks = async (date?: string): Promise<Task[]> => {
  const user = getUser();
  if (!user) return [];

  const d = date ?? getToday();

  const res = await fetch(`${ONBOARDING_API}/tasks/${user.id}/${d}`);
  if (!res.ok) throw new Error("Failed to fetch tasks");

  const data = await res.json();

  return data.map((t: any) => ({
    ...t,
    createdAt: t.created_at,
  }));
};

export const addTask = async (task: Omit<Task, "id" | "createdAt">): Promise<Task> => {
  const user = getUser();
  if (!user) throw new Error("Not authenticated");

  const res = await fetch(`${ONBOARDING_API}/tasks`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ ...task, userId: user.id }),
  });

  if (!res.ok) throw new Error("Failed to add task");

  const saved = await res.json();

  return {
    ...saved,
    createdAt: saved.created_at,
  };
};

export const toggleTask = async (taskId: string): Promise<void> => {
  const res = await fetch(`${ONBOARDING_API}/tasks/${taskId}/toggle`, {
    method: "PATCH",
  });

  if (!res.ok) throw new Error("Failed to toggle task");
};

export const deleteTask = async (taskId: string): Promise<void> => {
  const res = await fetch(`${ONBOARDING_API}/tasks/${taskId}`, {
    method: "DELETE",
  });

  if (!res.ok) throw new Error("Failed to delete task");
};


// Journal
// ============================
// ✅ JOURNAL (DB)
// ============================
export const getJournalEntries = async (): Promise<JournalEntry[]> => {
  const user = getUser();
  if (!user) return [];

  const res = await fetch(`${ONBOARDING_API}/journal/${user.id}`);
  if (!res.ok) throw new Error("Failed to fetch journal entries");

  const data = await res.json();

  return data.map((j: any) => ({
    id: j.id,
    date: j.date,
    content: j.content,
    mood: j.mood,
    tags: j.tags ?? [],
    autoGenerated: j.auto_generated ?? false,
    chatSummary: j.chat_summary ?? undefined,
    reflectionSummary: j.reflection_summary ?? undefined,
    createdAt: j.created_at,
  }));
};

export const addJournalEntry = async (
  entry: Omit<JournalEntry, "id" | "createdAt">
): Promise<JournalEntry> => {
  const user = getUser();
  if (!user) throw new Error("Not authenticated");

  const res = await fetch(`${ONBOARDING_API}/journal`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ ...entry, userId: user.id }),
  });

  if (!res.ok) throw new Error("Failed to add journal entry");

  const saved = await res.json();

  return {
    id: saved.id,
    date: saved.date,
    content: saved.content,
    mood: saved.mood,
    tags: saved.tags ?? [],
    autoGenerated: saved.auto_generated ?? false,
    chatSummary: saved.chat_summary ?? undefined,
    reflectionSummary: saved.reflection_summary ?? undefined,
    createdAt: saved.created_at,
  };
};


export const getJournalByDate = (date: string): JournalEntry | undefined => {
  return getJournalEntries().find(e => e.date === date);
};

// Reflections

// ============================
// ✅ REFLECTIONS (DB)
// ============================
export const getReflections = async (): Promise<Reflection[]> => {
  const user = getUser();
  if (!user) return [];

  const res = await fetch(`${ONBOARDING_API}/reflections/${user.id}`);
  if (!res.ok) throw new Error("Failed to fetch reflections");

  const data = await res.json();

  return data.map((r: any) => ({
    id: r.id,
    date: r.date,
    wins: r.wins ?? [],
    challenges: r.challenges ?? [],
    gratitude: r.gratitude ?? [],
    lessonsLearned: r.lessons_learned ?? "",
    mood: r.mood,
    energyLevel: r.energy_level ?? 5,
    createdAt: r.created_at,
  }));
};

export const addReflection = async (
  reflection: Omit<Reflection, "id" | "createdAt">
): Promise<Reflection> => {
  const user = getUser();
  if (!user) throw new Error("Not authenticated");

  const res = await fetch(`${ONBOARDING_API}/reflections`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ ...reflection, userId: user.id }),
  });

  if (!res.ok) throw new Error("Failed to add reflection");

  const saved = await res.json();

  return {
    id: saved.id,
    date: saved.date,
    wins: saved.wins ?? [],
    challenges: saved.challenges ?? [],
    gratitude: saved.gratitude ?? [],
    lessonsLearned: saved.lessons_learned ?? "",
    mood: saved.mood,
    energyLevel: saved.energy_level ?? 5,
    createdAt: saved.created_at,
  };
};

export const saveReflections = (reflections: Reflection[]) => {
  localStorage.setItem(KEYS.REFLECTIONS, JSON.stringify(reflections));
};

export const getReflectionByDate = (date: string): Reflection | undefined => {
  return getReflections().find(r => r.date === date);
};

// Chat History
export const getChatHistory = (): ChatMessage[] => {
  const data = localStorage.getItem(KEYS.CHAT_HISTORY);
  return data ? JSON.parse(data) : [];
};

export const saveChatHistory = (messages: ChatMessage[]) => {
  localStorage.setItem(KEYS.CHAT_HISTORY, JSON.stringify(messages));
};

export const addChatMessage = (message: Omit<ChatMessage, 'id' | 'timestamp'>): ChatMessage => {
  const newMessage: ChatMessage = {
    ...message,
    id: generateId(),
    timestamp: new Date().toISOString(),
  };
  const history = getChatHistory();
  history.push(newMessage);
  saveChatHistory(history);
  return newMessage;
};

export const clearChatHistory = () => {
  localStorage.removeItem(KEYS.CHAT_HISTORY);
};

// Achievements
// ============================
// ✅ ACHIEVEMENTS (DB)
// ============================
export const getAchievements = async (): Promise<Achievement[]> => {
  const user = getUser();
  if (!user) return [];

  const res = await fetch(`${ONBOARDING_API}/achievements/${user.id}`);
  if (!res.ok) throw new Error("Failed to fetch achievements");

  const data = await res.json();

  return data.map((a: any) => ({
    id: a.achievement_id ?? a.id,
    title: a.title,
    description: a.description,
    icon: a.icon,
    category: a.category,
    unlockedAt: a.unlocked_at ?? undefined,
  }));
};

export const unlockAchievement = async (id: string): Promise<void> => {
  const res = await fetch(`${ONBOARDING_API}/achievements/${id}/unlock`, {
    method: "PATCH",
  });

  if (!res.ok) throw new Error("Failed to unlock achievement");
};


// const defaultAchievements: Achievement[] = [
//   { id: 'first_habit', title: 'First Step', description: 'Complete your first habit', icon: '🌱', category: 'milestone' },
//   { id: 'streak_7', title: 'Week Warrior', description: 'Maintain a 7-day streak', icon: '🔥', category: 'streak' },
//   { id: 'streak_30', title: 'Monthly Master', description: 'Maintain a 30-day streak', icon: '⭐', category: 'streak' },
//   { id: 'first_reflection', title: 'Mindful Moment', description: 'Complete your first reflection', icon: '🧘', category: 'milestone' },
//   { id: 'journal_10', title: 'Story Teller', description: 'Write 10 journal entries', icon: '📖', category: 'milestone' },
//   { id: 'goals_3', title: 'Goal Getter', description: 'Set 3 goals', icon: '🎯', category: 'milestone' },
//   { id: 'morning_prep_7', title: 'Early Bird', description: 'Complete 7 morning preps', icon: '🌅', category: 'streak' },
//   { id: 'chat_coach_10', title: 'Open Mind', description: 'Have 10 coaching sessions', icon: '💬', category: 'milestone' },
// ];

// Settings
// ============================
// ✅ SETTINGS (DB)
// ============================
export const getSettings = async (): Promise<Settings> => {
  const user = getUser();
  if (!user) return defaultSettings;

  const res = await fetch(`${ONBOARDING_API}/settings/${user.id}`);
  if (!res.ok) throw new Error("Failed to fetch settings");

  const s = await res.json();

  return {
    notifications: s.notifications ?? true,
    morningPrepTime: s.morning_prep_time ?? "07:00",
    eveningReflectionTime: s.evening_reflection_time ?? "21:00",
    theme: (s.theme ?? "light") as Settings["theme"],
    privacy: {
      shareAnalytics: s.share_analytics ?? false,
      showStreak: s.show_streak ?? true,
    },
  };
};

export const saveSettings = async (settings: Settings): Promise<void> => {
  const user = getUser();
  if (!user) return;

  const res = await fetch(`${ONBOARDING_API}/settings/${user.id}`, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(settings),
  });

  if (!res.ok) throw new Error("Failed to update settings");
};


const defaultSettings: Settings = {
  notifications: true,
  morningPrepTime: '07:00',
  eveningReflectionTime: '21:00',
  theme: 'light',
  privacy: {
    shareAnalytics: false,
    showStreak: true,
  },
};

// Onboarding
export const setOnboardingComplete = async () => {
  const user = getUser();
  if (!user) return;

  await fetch(`${ONBOARDING_API}/complete`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ userId: user.id }),
  });

  localStorage.setItem(KEYS.ONBOARDING_COMPLETE, 'true');
};

export const isOnboardingComplete = async (): Promise<boolean> => {
  const user = getUser();
  if (!user) return false;

  const res = await fetch(`${ONBOARDING_API}/status/${user.id}`);
  const data = await res.json();
  return data.completed;
};


// Helper to get today's date string
export const getTodayString = () => getToday();
